import lab1 from "../lab_images/lab1.jpeg";
import lab2 from "../lab_images/lab2.jpg";
import lab3 from "../lab_images/lab3.jpeg";
import lab4 from "../lab_images/lab4.jpeg";
import lab5 from "../lab_images/lab5.jpeg";
import lab6 from "../lab_images/lab6.jpeg";
import lab7 from "../lab_images/lab7.jpeg";
import lab8 from "../lab_images/lab8.jpg";

const Blood_data = [
  {
    id: 1,
    name: "blood test",
    lab_name: "aravam labs",
    timings: "10:00 AM - 8:00 PM",
    address: "Faridabad, India",
    consultation_fee: 300,
    img: lab1,
  },
  {
    id: 2,
    name: "blood test",
    lab_name: "saguna Tests",
    timings: "9:00 AM - 9:00 PM",
    address: "palai, India",
    consultation_fee: 250,
    img:lab2,

  },

  {
    id: 3,
    name: "blood test",
    lab_name: "red cross labs",
    timings: "8:00 AM - 6:00 PM",
    address: "Chennai, India",
    consultation_fee: 400,
    img:lab3,
  },
  {
    id: 4,
    name: "blood test",
    lab_name: "prime diagnostics",
    timings: "7:00 AM - 5:00 PM",
    address: "Mumbai, India",
    consultation_fee: 350,
    img:lab4,
  },
  {
    id: 5,
    name: "blood test",
    lab_name: "care labs",
    timings: "9:00 AM - 7:00 PM",
    address: "Bangalore, India",
    consultation_fee: 280,
    img:lab5,
  },

  {
    id: 6,
    name: "blood test",
    lab_name: "health plus labs",
    timings: "8:30 AM - 7:30 PM",
    address: "Hyderabad, India",
    consultation_fee: 320,
    img:lab6,
  },
  {
    id: 7,
    name: "blood test",
    lab_name: "wellness diagnostics",
    timings: "9:00 AM - 8:00 PM",
    address: "Pune, India",
    consultation_fee: 290,
    img:lab7,
  },
  {
    id: 8,
    name: "blood test",
    lab_name: "precision labs",
    timings: "10:00 AM - 6:00 PM",
    address: "Delhi, India",
    consultation_fee: 300,
    img:lab8,
  },
  {
    id: 9,
    name: "blood test",
    lab_name: "lifeline labs",
    timings: "8:00 AM - 5:00 PM",
    address: "Kolkata, India",
    consultation_fee: 270,
    img:lab3,
  },
  {
    id: 10,
    name: "blood test",
    lab_name: "apollo diagnostics",
    timings: "7:30 AM - 6:30 PM",
    address: "Bhopal, India",
    consultation_fee: 310,
    img:lab1,

  },
  {
    id: 11,
    name: "blood test",
    lab_name: "medilabs",
    timings: "8:00 AM - 7:00 PM",
    address: "Jaipur, India",
    consultation_fee: 340,
    img:lab2,
  },
  {
    id: 12,
    name: "blood test",
    lab_name: "city care labs",
    timings: "9:00 AM - 6:00 PM",
    address: "Lucknow, India",
    consultation_fee: 260,
    img:lab4,
  },
  {
    id: 13,
    name: "blood test",
    lab_name: "quick labs",
    timings: "8:30 AM - 7:30 PM",
    address: "Indore, India",
    consultation_fee: 290,
    img:lab5,
  },
  {
    id: 14,
    name: "blood test",
    lab_name: "accurate labs",
    timings: "9:00 AM - 8:00 PM",
    address: "Nagpur, India",
    consultation_fee: 350,
    img:lab6,
  },
  {
    id: 15,
    name: "blood test",
    lab_name: "sunshine diagnostics",
    timings: "8:00 AM - 7:00 PM",
    address: "Patna, India",
    consultation_fee: 300,
    img:lab7,
  },
  {
    id: 16,
    name: "blood test",
    lab_name: "health care labs",
    timings: "9:30 AM - 6:30 PM",
    address: "Guwahati, India",
    consultation_fee: 310,
    img:lab8,
  },
  {
    id: 17,
    name: "blood test",
    lab_name: "genius diagnostics",
    timings: "8:00 AM - 5:00 PM",
    address: "Kochi, India",
    consultation_fee: 270,
    img:lab1,
  },
  {
    id: 18,
    name: "blood test",
    lab_name: "medisafe labs",
    timings: "9:00 AM - 7:00 PM",
    address: "Surat, India",
    consultation_fee: 340,
    img:lab2,
  },
  {
    id: 19,
    name: "blood test",
    lab_name: "reliable diagnostics",
    timings: "8:30 AM - 7:30 PM",
    address: "Vadodara, India",
    consultation_fee: 320,
    img:lab3,
  },
  {
    id: 20,
    name: "blood test",
    lab_name: "diagnostics plus",
    timings: "7:00 AM - 6:00 PM",
    address: "Nashik, India",
    consultation_fee: 290,
    img:lab4,
  },
  {
    id: 21,
    name: "blood test",
    lab_name: "swift labs",
    timings: "9:00 AM - 5:00 PM",
    address: "Rajkot, India",
    consultation_fee: 310,
    img:lab5,
  },
  {
    id: 22,
    name: "blood test",
    lab_name: "trust care labs",
    timings: "8:00 AM - 6:00 PM",
    address: "Chandigarh, India",
    consultation_fee: 330,
    img:lab6,
  },

];

export default Blood_data;
