import React from "react";
import img1 from "../assets/doc_1.jpg";
import img2 from "../assets/doc_2.jpg";
import img3 from "../assets/doc_3.jpg";
import img4 from "../assets/doc_4.jpg";
import img5 from "../assets/doc_5.jpg";
import img6 from "../assets/doc_6.jpg";
import img7 from "../assets/doc_7.jpg";
import img8 from "../assets/doc_8.jpg";
import img9 from "../assets/doc_9.jpg";
import img0 from "../assets/doc_0.jpg";

const Doc_data = [
  {
    id: 1,
    name: "Dr. Patrick Smith",
    spec: "Dentist",
    img: img9,
    address: "Noida, Mumbai",
    consultation_fee: 200,
    rating: 4.5,
    experience: "10 years",
    hospital: "Apollo Hospitals",
    education: "MBBS, BDS Dental",
    doctors_advice:
      "Maintain good oral hygiene by brushing twice a day and flossing regularly. Avoid sugary foods and drinks. Visit your dentist every six months for check-ups. Early detection of dental issues can prevent complex treatments.",
  },
  {
    id: 2,
    name: "Dr. Jane White",
    spec: "Dermatologist",
    img: img7,
    address: "Vizag, AP",
    consultation_fee: 500,
    rating: 4.1,
    experience: "5 years",
    hospital: "Lalitha Specialty",
    education: "MBBS, MD Dermatology",
    doctors_advice:
      "Protect your skin from harmful UV rays by using sunscreen daily. Stay hydrated and maintain a healthy diet rich in fruits and vegetables. Avoid using harsh skin products. Consult a dermatologist for persistent skin issues.",
  },
  {
    id: 3,
    name: "Dr. Brook Henry",
    spec: "Dentist",
    img: img1,
    address: "Noida, Mumbai",
    consultation_fee: 180,
    rating: 4.2,
    experience: "10 years",
    hospital: "Care U Hospital",
    education: "BDS, MDS",
    doctors_advice:
      "Brush your teeth with fluoride toothpaste and use mouthwash to reduce plaque. Avoid smoking and excessive alcohol consumption. Schedule regular dental cleanings. Address any dental issues promptly to avoid complications.",
  },
  {
    id: 4,
    name: "Dr. Emily Johnson",
    spec: "Pediatrician",
    img: img6,
    address: "Delhi, India",
    consultation_fee: 700,
    rating: 4.7,
    experience: "8 years",
    hospital: "Star Hospitals",
    education: "MBBS, MD Pediatrics",
    doctors_advice:
      "Ensure your child gets regular vaccinations as recommended. Encourage a balanced diet and regular physical activity. Schedule routine check-ups to monitor growth and development. Address any developmental or behavioral concerns early.",
  },
  {
    id: 5,
    name: "Dr. Michael Brown",
    spec: "Cardiologist",
    img: img5,
    address: "Gurgaon, Mumbai",
    consultation_fee: 200,
    rating: 4.9,
    experience: "15 years",
    hospital: "Apollo Hospitals",
    education: "MBBS, DM Cardiology",
    doctors_advice:
      "Maintain a healthy diet low in saturated fats and high in fiber. Exercise regularly and avoid smoking. Monitor your blood pressure and cholesterol levels. Follow prescribed medications and consult regularly for heart health.",
  },
  {
    id: 6,
    name: "Dr. Sarah Lee",
    spec: "Gynecologist",
    img: img4,
    address: "Faridabad, India",
    consultation_fee: 900,
    rating: 4.6,
    experience: "12 years",
    hospital: "Promise Clinic",
    education: "MBBS, MD Gynecology",
    doctors_advice:
      "Schedule regular gynecological check-ups and screenings. Maintain a balanced diet and exercise regularly. Practice safe sex and get tested for sexually transmitted infections. Discuss any unusual symptoms with your gynecologist.",
  },
  {
    id: 7,
    name: "Dr. David Wilson",
    spec: "Orthopedic Surgeon",
    img: img3,
    address: "Noida, Mumbai",
    consultation_fee: 500,
    rating: 4.9,
    experience: "20 years",
    hospital: "Care Hospitals",
    education: "MBBS, MS Orthopedics",
    doctors_advice:
      "Engage in regular physical activity to strengthen bones and muscles. Use proper techniques during exercise to prevent injuries. Maintain a healthy weight and avoid excessive strain on joints. Seek early treatment for persistent joint or bone pain.",
  },
  {
    id: 8,
    name: "Dr. Olivia Martinez",
    spec: "Neurologist",
    img: img0,
    address: "Delhi, India",
    consultation_fee: 300,
    rating: 4.4,
    experience: "18 years",
    hospital: "Health Choice Hospitals",
    education: "MBBS, MD Neurology",
    doctors_advice:
      "Engage in mental exercises to keep your brain active. Maintain a healthy lifestyle with a balanced diet and regular physical activity. Monitor and manage chronic conditions such as diabetes that may affect neurological health. Consult a neurologist for persistent headaches or cognitive issues.",
  },
  {
    id: 9,
    name: "Dr. Patrick Reed",
    spec: "Endocrinologist",
    img: img2,
    address: "Gurgaon, India",
    consultation_fee: 400,
    rating: 4.3,
    experience: "14 years",
    hospital: "Shine Hospital",
    education: "MBBS, DM Endocrinology",
    doctors_advice:
      "Maintain a balanced diet to manage hormone levels effectively. Regularly monitor blood sugar and thyroid levels. Exercise regularly to support endocrine function. Consult your endocrinologist for hormonal imbalances or metabolic disorders.",
  },
  {
    id: 10,
    name: "Dr. Sophia Anderson",
    spec: "Ophthalmologist",
    img: img8,
    address: "Noida, Mumbai",
    consultation_fee: 950,
    rating: 4.6,
    experience: "11 years",
    hospital: "Care Hospitals",
    education: "MBBS, MS Ophthalmology",
    doctors_advice:
      "Get regular eye exams to detect issues early. Protect your eyes from excessive UV exposure by wearing sunglasses. Maintain a healthy diet rich in vitamins and minerals for eye health. Address any vision changes promptly with your ophthalmologist.",
  },
  {
    id: 11,
    name: "Dr. Daniel Thompson",
    spec: "Pulmonologist",
    img: img1,
    address: "Delhi, India",
    consultation_fee: 1000,
    rating: 4.5,
    experience: "9 years",
    hospital: "Lalitha Specialty",
    education: "MBBS, MD Pulmonology",
    doctors_advice:
      "Avoid smoking and exposure to pollutants to protect your lungs. Practice breathing exercises and maintain good air quality in your environment. Regularly monitor lung function if you have respiratory conditions. Consult your pulmonologist for persistent cough or breathing difficulties.",
  },
  {
    id: 12,
    name: "Dr. Isabella Taylor",
    spec: "Rheumatologist",
    img: img7,
    address: "Gurgaon, India",
    consultation_fee: 800,
    rating: 4.7,
    experience: "13 years",
    hospital: "Apollo",
    education: "MBBS, DM Rheumatology",
    doctors_advice:
      "Engage in regular physical activity to manage joint pain. Follow a balanced diet rich in anti-inflammatory foods. Adhere to prescribed medications and treatments. Consult your rheumatologist for flare-ups or new symptoms.",
  },
  {
    id: 13,
    name: "Dr. Lucas Harris",
    spec: "Hematologist",
    img: img9,
    address: "Faridabad, India",
    consultation_fee: 950,
    rating: 4.8,
    experience: "7 years",
    education: "MBBS, DM Hematology",
    doctors_advice:
      "Monitor your blood health through regular tests. Maintain a nutritious diet to support healthy blood production. Avoid activities that may lead to excessive bleeding or bruising. Seek medical advice for unusual symptoms like fatigue or frequent infections.",
  },
  {
    id: 14,
    name: "Dr. Mia Clark",
    spec: "Allergist",
    img: img6,
    address: "Delhi, India",
    consultation_fee: 850,
    rating: 4.4,
    experience: "6 years",
    hospital: "Lalitha Specialty",
    education: "MBBS, MD Allergy",
    doctors_advice:
      "Identify and avoid allergens that trigger symptoms. Keep a record of allergy symptoms and triggers. Use prescribed medications or treatments as directed. Consult your allergist for persistent or severe allergic reactions.",
  },
  {
    id: 15,
    name: "Dr. Ethan Robinson",
    spec: "Plastic Surgeon",
    img: img6,
    address: "Guntur, India",
    consultation_fee: 1500,
    rating: 4.9,
    experience: "14 years",
    education: "MBBS, MCh Plastic Surgery",
    doctors_advice:
      "Ensure you have realistic expectations for cosmetic procedures. Follow pre- and post-operative care instructions carefully. Maintain a healthy lifestyle for optimal results. Consult your plastic surgeon for any concerns or complications.",
  },
  {
    id: 16,
    name: "Dr. Ava Martinez",
    spec: "Urologist",
    img: img4,
    address: "Noida",
    consultation_fee: 950,
    rating: 4.6,
    experience: "10 years",
    hospital: "Apollo",
    education: "MBBS, MS Urology",
    doctors_advice:
      "Stay hydrated and maintain a healthy diet to support urinary health. Seek medical advice for any unusual urinary symptoms or pain. Regular check-ups are important for monitoring urinary function. Follow prescribed treatments and lifestyle recommendations.",
  },
  {
    id: 17,
    name: "Dr. Benjamin Wilson",
    spec: "Endocrinologist",
    img: img3,
    address: "Delhi, India",
    consultation_fee: 800,
    rating: 4.3,
    experience: "12 years",
    hospital: "Lalitha Specialty",
    education: "MBBS, DM Endocrinology",
    doctors_advice:
      "Monitor your blood sugar levels regularly if you have diabetes. Maintain a balanced diet and exercise regimen. Follow prescribed medications and treatments for endocrine disorders. Consult your endocrinologist for any changes in symptoms.",
  },
  {
    id: 18,
    name: "Dr. Harper Evans",
    spec: "Gastroenterologist",
    img: img0,
    address: "Hyderabad, India",
    consultation_fee: 1100,
    rating: 4.7,
    experience: "16 years",
    education: "MBBS, DM Gastroenterology",
    doctors_advice:
      "Maintain a diet that supports digestive health and avoid irritants. Stay hydrated and practice regular physical activity. Consult for persistent digestive symptoms or discomfort. Regular screenings are important for early detection of gastrointestinal issues.",
  },
  {
    id: 19,
    name: "Dr. Ella White",
    spec: "Nephrologist",
    img: img2,
    address: "Delhi, India",
    consultation_fee: 1050,
    rating: 4.5,
    experience: "14 years",
    hospital: "Care Hospitals",
    education: "MBBS, DM Nephrology",
    doctors_advice:
      "Monitor kidney function regularly and manage chronic conditions like diabetes. Maintain a healthy diet low in salt and protein. Stay hydrated and avoid excessive use of over-the-counter medications. Consult for any symptoms related to kidney health.",
  },
  {
    id: 20,
    name: "Dr. Jacob King",
    spec: "Oncologist",
    img: img8,
    address: "Gurgaon, India",
    consultation_fee: 1300,
    rating: 4.9,
    experience: "20 years",
    hospital: "Apollo",
    education: "MBBS, DM Oncology",
    doctors_advice:
      "Follow a balanced diet and maintain a healthy lifestyle. Regular screenings are important for early cancer detection. Adhere to prescribed treatments and manage side effects. Consult your oncologist for any changes in symptoms or health status.",
  },
  {
    id: 21,
    name: "Dr. Amelia Scott",
    spec: "Psychiatrist",
    img: img1,
    address: "Noida, India",
    consultation_fee: 1200,
    rating: 4.6,
    experience: "17 years",
    hospital: "Lalitha Specialty",
    education: "MBBS, MD Psychiatry",
    doctors_advice:
      "Seek help if you experience persistent feelings of sadness or anxiety. Engage in regular mental health check-ups. Practice stress-reducing techniques such as mindfulness or therapy. Follow prescribed treatments and consult for any mental health concerns.",
  },
  {
    id: 22,
    name: "Dr. Olivia Green",
    spec: "Pulmonologist",
    img: img7,
    address: "Delhi, India",
    consultation_fee: 950,
    rating: 4.4,
    experience: "8 years",
    hospital: "Care Hospitals",
    education: "MBBS, MD Pulmonology",
    doctors_advice:
      "Avoid exposure to pollutants and allergens that can affect lung health. Practice breathing exercises and maintain a healthy lifestyle. Follow treatment plans for chronic respiratory conditions. Consult for persistent respiratory issues or symptoms.",
  },
];

export default Doc_data;
