const Doc_data = [
  {
    name: "Dr. patrick Smith",
    spec: "Dentist",
    img: "./assets/doc_9.jpg",
    adress: "Noida,mumbai",
    consultation_fee: 200,
    rating: 4.5,
    experience: "10 years",
    hospital: "Apollo hospitals",
  },
  {
    name: "Dr. Jane white",
    spec: "Dermatologist",
    img: "./assets/doc_7.jpg",
    adress: "vizag,AP",
    consultation_fee: "500",
    rating: 4.1,
    experience: "5 years",
    hospital: "lalitha specality",
  },

  {
    name: "Dr. brook henry",
    spec: "Dentist",
    img: "./assets/doc_1.jpg",
    adress: "Noida",
    consultation_fee: "180",
    rating: 4.2,
    experience: "10 years",
    hospital: "Care U hospital",
  },
  {
    name: "Dr. Emily Johnson",
    spec: "Pediatrician",
    img: "./assets/doc_6.jpg",
    address: "Delhi",
    consultation_fee: "700",
    rating: 4.7,
    experience: "8 years",
    hospital: "star hospitals",
  },
  {
    name: "Dr. Michael Brown",
    spec: "Cardiologist",
    img: "./assets/doc_5.jpg",
    address: "Gurgaon",
    consultation_fee: "200",
    rating: 4.9,
    experience: "15 years",
    hospital: "Apollo hospitals",
  },
  {
    name: "Dr. Sarah Lee",
    spec: "Gynecologist",
    img: "./assets/doc_4.jpg",
    address: "Faridabad",
    consultation_fee: "900",
    rating: 4.6,
    experience: "12 years",
    hospital: "promise clinic",
  },
  {
    name: "Dr. David Wilson",
    spec: "Orthopedic Surgeon",
    img: "./assets/doc_3.jpg",
    address: "Noida",
    consultation_fee: "500",
    rating: 4.9,
    experience: "20 years",
    hospital: " care hospitals",
  },
  {
    name: "Dr. Olivia Martinez",
    spec: "Neurologist",
    img: "./assets/doc_0.jpg",
    address: "Delhi",
    consultation_fee: "300",
    rating: 4.4,
    experience: "18 years",
    hospital: "health choice hospitals",
  },
  {
    name: "Dr.patrick reed",
    spec: "Endocrinologist",
    img: "./assets/doc_2.jpg",
    address: "Gurgaon",
    consultation_fee: "400",
    rating: 4.3,
    experience: "14 years",
    hospital: "shine hospital",
  },
  {
    name: "Dr. Sophia Anderson",
    spec: "Ophthalmologist",
    img: "./assets/doc_8.jpg",
    address: "Noida",
    consultation_fee: "950",
    rating: 4.6,
    experience: "11 years",
    hospital: " care hospitals",
  },
  {
    name: "Dr. Daniel Thompson",
    spec: "Pulmonologist",
    img: "./assets/doc_1.jpg",
    address: "Delhi",
    consultation_fee: "1000",
    rating: 4.5,
    experience: "9 years",
    hospital: "lalitha specality",
  },
  {
    name: "Dr. Isabella Taylor",
    spec: "Rheumatologist",
    img: "./assets/doc_7.jpg",
    address: "Gurgaon",
    consultation_fee: "800",
    rating: 4.7,
    experience: "13 years",
    hospital: "Apollo",
  },
  {
    name: "Dr. Lucas Harris",
    spec: "Hematologist",
    img: "./assets/doc_9.jpg",
    address: "Faridabad",
    consultation_fee: "950",
    rating: 4.8,
    experience: "7 years",
  },
  {
    name: "Dr. Mia Clark",
    spec: "Allergist",
    img: "./assets/doc_6.jpg",
    address: "Delhi",
    consultation_fee: "850",
    rating: 4.4,
    experience: "6 years",
    hospital: "lalitha specality",
  },
  {
    name: "Dr. Ethan Robinson",
    spec: "Plastic Surgeon",
    img: "./assets/doc_5.jpg",
    address: "Gurgaon",
    consultation_fee: "1500",
    rating: 4.9,
    experience: "14 years",
  },
  {
    name: "Dr. Ava Martinez",
    spec: "Urologist",
    img: "./assets/doc_4.jpg",
    address: "Noida",
    consultation_fee: "950",
    rating: 4.6,
    experience: "10 years",
    hospital: "Apollo",
  },
  {
    name: "Dr. Benjamin Wilson",
    spec: "Endocrinologist",
    img: "./assets/doc_3.jpg",
    address: "Delhi",
    consultation_fee: "800",
    rating: 4.3,
    experience: "12 years",
    hospital: "lalitha specality",
  },
  {
    name: "Dr. Harper Evans",
    spec: "Gastroenterologist",
    img: "./assets/doc_0.jpg",
    address: "Faridabad",
    consultation_fee: "1100",
    rating: 4.7,
    experience: "16 years",
  },
  {
    name: "Dr. Ella White",
    spec: "Nephrologist",
    img: "./assets/doc_2.jpg",
    address: "Delhi",
    consultation_fee: "1050",
    rating: 4.5,
    experience: "14 years",
    hospital: " care hospitals",
  },
  {
    name: "Dr. Jacob King",
    spec: "Oncologist",
    img: "./assets/doc_8.jpg",
    address: "Gurgaon",
    consultation_fee: "1300",
    rating: 4.9,
    experience: "20 years",
    hospital: "Apollo",
  },
  {
    name: "Dr. Amelia Scott",
    spec: "Psychiatrist",
    img: "./assets/doc_1.jpg",
    address: "Noida",
    consultation_fee: "1200",
    rating: 4.6,
    experience: "17 years",
    hospital: "lalitha specality",
  },
  {
    name: "Dr. Olivia Green",
    spec: "Pulmonologist",
    img: "./assets/doc_7.jpg",
    address: "Delhi",
    consultation_fee: "950",
    rating: 4.4,
    experience: "8 years",
    hospital: " care hospitals",
  },
];

export default Doc_data;
