const removeDuplicates = (array) => {
  return [...new Set(array)];
};

// Example usage
const SuggestionList = [
  "Cardiologist",
  "Dermatologist",
  "Neurologist",
  "Orthopedic",
  "Pediatrician",
  "Psychiatrist",
  "Rheumatologist",
  "Urologist",
  "Oncologist",
  "Endocrinologist",
  "Ophthalmologist",
  "Gastroenterologist",
  "Pulmonologist",
  "Hematologist",
  "Allergist",
  "Nephrologist",
  "Gynaecologist",
  "Plastic Surgeon",
  "Orthopedic",
  "Dentist",
  "Dermatologist",
  "Urologist",
  "Neurologist",
  "General Physician",
  "Pediatrician",
  "Psychiatrist",
  "Rheumatologist",
  "Urologist",
  "Oncologist",
  "Endocrinologist",
  "Ophthalmologist",
  "Pulmonologist",
  "Hematologist",
  "Allergist",
  "Nephrologist",
  "Gynaecologist",
  "Plastic Surgeon",
  "Orthopedic",
  "Dentist",
  "Dermatologist",
  "Urologist",
  "Neurologist",
  "General Physician",
  "Pediatrician",
  "Psychiatrist",
  "Rheumatologist",
  "Urologist",
  "Oncologist",
  "Endocrinologist",
  "Ophthalmologist",
  "Gastroenterologist",
  "Pulmonologist",
  "Hematologist",
  "Allergist",
  "Nephrologist",
  "Gynaecologist",
  "Plastic Surgeon",
  "Orthopedic",
  "Dentist",
  "Dermatologist",
  "Ayurveda",
  "Gum Dentist",
  "Addiction Medicine",
  "Anesthesiology",
  "Cardiology",
  "Critical Care Medicine",
  "Dermatology",
  "Emergency Medicine",
  "Endocrinology",
  "Family Medicine",
  "Gastroenterology",
  "Geriatrics",
  "Hematology",
  "Infectious Disease",
  "Internal Medicine",
  "Nephrology",
  "Neurology",
  "Obstetrics and Gynecology",
  "Oncology",
  "Ophthalmology",
  "Orthopedic Surgery",
  "Otolaryngology (ENT)",
  "Palliative Care",
  "Pediatrics",
  "Plastic Surgery",
  "Preventive Medicine",
  "Psychiatry",
  "Pulmonology",
  "Rheumatology",
  "Sports Medicine",
  "Surgery",
  "Urology",
  "Vascular Surgery",
];

export default removeDuplicates(SuggestionList)
