const removeDuplicates = (array) => {
  return [...new Set(array)];
};

const SuggestionTest = [
  "Blood Test",
  "Urine Test",
  "X-ray",
  "MRI",
  "CT Scan",
  "Ultrasound",
  "ECG",
  "Blood Sugar Test",
  "Liver Function Test",
  "Kidney Function Test",
  "Thyroid Test",
  "CBC (Complete Blood Count)",
  "Blood Pressure Test",
  "Cholesterol Test",
  "Bone Density Scan",
  "Mammogram",
  "Pap Smear",
  "Prostate Specific Antigen (PSA) Test",
  "Hemoglobin A1C Test",
  "Lipid Panel",
  "Pulmonary Function Test",
  "Echocardiogram",
  "Stress Test",
  "HIV Test",
  "Hepatitis B Test",
  "Hepatitis C Test",
  "Allergy Test",
  "Vitamin D Test",
  "Calcium Test",
  "Rheumatoid Factor (RF) Test",
  "C-Reactive Protein (CRP) Test",
  "Serum Ferritin Test",
  "Stool Test",
  "Sputum Culture",
  "Spirometry",
  "Skin Biopsy",
  "Electrolyte Panel",
  "Genetic Testing",
  "Glucose Tolerance Test",
  "Colonoscopy",
  "Bone Marrow Transplant",
  "Cervical Cancer Screening",
  "Cervical Cancer Risk Assessment",
  "Cervical Cancer Treatment",
  "Cervical Cancer Prevention",
  "Cervical Cancer Diagnosis",
  "Cervical Cancer Management",
  "sugar test",
  "glucose test",
  "blood sugar test",
  "sugar tolerance test",
  "glucose tolerance test",
  "blood sugar tolerance test",
  "sugar management test",
  "glucose management test",
  "blood sugar management test",
  "sugar prevention test",
  "glucose prevention test",
  "blood sugar prevention test",
  "pregnancy test",
  "postpartum test",
  "infertility test",
  "childbirth test",
  "childhood test",
  "motherhood test",
  "infant test",
  "sugar CSF test",
  "glucose CSF test",
  "blood sugar CSF test",
  "sugar tolerance CSF test",
  "glucose tolerance CSF test",
  "Throat Swab",
  "Chest X-ray",
  "Chest CT Scan",
  "Chest X-ray",
  "Chest CT Scan",
  "thyroid test",
  "thyroid profile",
  "thyroid function test",
  "eye checkup",
  "liver function test",
  "nose checkup",
  "kidney function test",
  "blood test",
  

];

export default removeDuplicates(SuggestionTest);
